---
title: "day 4 functions and loops"
author: "Angie Starrett"
date: "2023-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r load packages}
library(tidyverse)
library(here)

```
```{r examine SB county}
sbc <- read_csv(here('county_data/santa_barbara.csv'))

ggplot(sbc, aes(x = income, y = math)) + geom_point() + theme_minimal()

```

```{r summarize SB county}

sbc_summary <- sbc %>% 
  group_by(grades) %>%
  summarize(mean_inc = mean(income),
            mean_read = mean(read),
            mean_math = mean(math, na.rm = TRUE))
write_csv(sbc_summary, here('county_data_summary/santa_barbara.csv'))

```

loop through files in county_data
read the csv
for each file group by grades and create summary data file of emans for income, read & math
write a csv to county_data_summary for each county_data file

```{r for loop}
vec <- 1:20
for(x in vec) {
  print(x * 2)
}

month_vec <- month.name
for(m in month_vec) {
  x <- paste(m, '2023')
  print(x)
}
```

```{r}
f_vec <- list.files(here('county_data'), full.names = TRUE)

for(f in f_vec) {
  # f <- f_vec[1]
  cty_df <- read_csv(f, show_col_types = FALSE)
                     
cty_summary <- cty_df %>% 
  group_by(grades) %>%
  summarize(mean_inc = mean(income),
            mean_read = mean(read),
            mean_math = mean(math))
f_out <- here('county_data_summary', basename(f))
write_csv(cty_summary, f_out)
}
```

## Functions Introduction

```{r}
square <- function(x) {
  y <- x^2
  return(y)
}

square(11)

square2 <- function(x, pow = 3) {
  y <- x^pow
  return(y)
}

square2(3)
```

```{r}
  process_county <- function(f) {
  cty_df <- read_csv(f, show_col_types = FALSE)
         
cty_summary <- cty_df %>% 
    group_by(grades) %>%
  summarize(mean_inc = mean(income),
            mean_read = mean(read),
            mean_math = mean(math)) 
  
f_out <- here('county_data_summary', basename(f))
write_csv(cty_summary, f_out)
return(cty_summary)
  }  
```
```{r}

f_vec <- list.files(here('county_data'), full.names = TRUE)

for(f in f_vec) {
  # f <- f_vec[1]
 x <- process_county(f)
}
```

```{r}
lapply(X = 1:20, FUN = function(x) x^2)
tmp_list <- lapply(X = f_vec, FUN = process_county)

county_list <- lapply(X = f_vec,
                      FUN = read_csv,
                      show_col_types = FALSE) 
all_county_df <- bind_rows(county_list)
write_csv(all_county_df, here('data/ca_schools.csv'))
```




